### PR TITLE
feat: add loading spinner instead ov own view

### PR DESCRIPTION
**Pull request by 21adrian1996**
# Checklist (Only for frontend changes)
- [ ] Changes tested in IE11
- [x] Responsive
- [x] Documented "How to use it"
- [ ] Documented "How to install"
- [x] Featured in Styleguide

# Summary of this PR

### CODE REVIEW

**Review by JonasNiestroj — COMMENTED** [review]
As far as i know we have a directive for loading.
You can use it with v-loading on the elements. Is there a reason to go for a component instead of a directive? Also i think with your css changes the loading directive is not longer working

**Comment by 21adrian1996** [comment]
@JonasNiestroj 
With the component, we have the loading state in the store and can start and stop it by calling the store methods and do not need to define any directives anywhere. The component is generally loaded and with the state stored, we can redirect in vue while showing the spinner.

In my opinion it is more flexibel and easier to use like this, but If there are any good reasons not to change this, we can discuss this.

**Comment by JonasNiestroj** [comment]
@21adrian1996 Good point. Is it possible to still have a version where the directive is working as before? The directive is good for the cases where you just want to display the loading state on a specific element (e.g. a table) Then we would have the "global" loading and the "local" loading

**Comment by 21adrian1996** [comment]
@JonasNiestroj 

That seems to be very reasonable. Did not think of local loading states while deleting it.
It is now possible to use both (local and global) in the same project.
Also the styling (coloring, icon, background) is now the same for both cases.

**Pull request closed without merging**
